name: Sign iOS Shortcut
on:
  workflow_dispatch:
    inputs:
      shortcut_name:
        description: "Name of the shortcut (without .shortcut)"
        required: true

jobs:
  sign:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sign Shortcut
        run: |
          mkdir -p signed_shortcuts
          shortcuts sign unsigned_shortcuts/${{ github.event.inputs.shortcut_name }}.shortcut --output signed_shortcuts/${{ github.event.inputs.shortcut_name }}-signed.shortcut

      - name: Upload signed shortcut
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.shortcut_name }}-signed
          path: signed_shortcuts/${{ github.event.inputs.shortcut_name }}-signed.shortcut
